"""
rules.py — Strict, comprehensive extension classification rules.

Each entry maps a lowercase extension → Rule(category, subcategory, mime_type, description)
"""
from __future__ import annotations
from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Rule:
    category: str
    subcategory: str
    mime_type: str
    description: str


def _r(cat: str, sub: str, mime: str, desc: str) -> Rule:
    return Rule(cat, sub, mime, desc)


EXTENSION_RULES: dict[str, Rule] = {
    # ── Images ──────────────────────────────────────────────────────────────
    "jpg":    _r("Images", "Photos",     "image/jpeg",           "JPEG photo"),
    "jpeg":   _r("Images", "Photos",     "image/jpeg",           "JPEG photo"),
    "png":    _r("Images", "Graphics",   "image/png",            "PNG graphic"),
    "gif":    _r("Images", "Animated",   "image/gif",            "GIF animation"),
    "bmp":    _r("Images", "Graphics",   "image/bmp",            "Bitmap image"),
    "tiff":   _r("Images", "Photos",     "image/tiff",           "TIFF photo"),
    "tif":    _r("Images", "Photos",     "image/tiff",           "TIFF photo"),
    "webp":   _r("Images", "Web",        "image/webp",           "WebP image"),
    "avif":   _r("Images", "Web",        "image/avif",           "AVIF image"),
    "svg":    _r("Images", "Vector",     "image/svg+xml",        "SVG vector graphic"),
    "ico":    _r("Images", "Icons",      "image/x-icon",         "Icon file"),
    "icns":   _r("Images", "Icons",      "image/x-icns",         "macOS icon"),
    "heic":   _r("Images", "Photos",     "image/heic",           "HEIC photo"),
    "heif":   _r("Images", "Photos",     "image/heif",           "HEIF photo"),
    "raw":    _r("Images", "Raw",        "image/x-raw",          "Camera RAW"),
    "cr2":    _r("Images", "Raw",        "image/x-canon-cr2",    "Canon RAW"),
    "cr3":    _r("Images", "Raw",        "image/x-canon-cr3",    "Canon RAW 3"),
    "nef":    _r("Images", "Raw",        "image/x-nikon-nef",    "Nikon RAW"),
    "arw":    _r("Images", "Raw",        "image/x-sony-arw",     "Sony RAW"),
    "dng":    _r("Images", "Raw",        "image/x-adobe-dng",    "Adobe DNG"),
    "orf":    _r("Images", "Raw",        "image/x-olympus-orf",  "Olympus RAW"),
    "rw2":    _r("Images", "Raw",        "image/x-panasonic-rw2","Panasonic RAW"),
    "psd":    _r("Images", "Layered",    "image/vnd.adobe.photoshop","Photoshop"),
    "psb":    _r("Images", "Layered",    "image/vnd.adobe.photoshop","Photoshop Large"),
    "xcf":    _r("Images", "Layered",    "image/x-xcf",          "GIMP project"),
    "ai":     _r("Images", "Vector",     "application/postscript","Adobe Illustrator"),
    "eps":    _r("Images", "Vector",     "application/postscript","Encapsulated PS"),

    # ── Videos ──────────────────────────────────────────────────────────────
    "mp4":    _r("Videos", "Standard",  "video/mp4",            "MPEG-4 video"),
    "m4v":    _r("Videos", "Apple",     "video/x-m4v",          "iTunes video"),
    "mkv":    _r("Videos", "Standard",  "video/x-matroska",     "Matroska video"),
    "avi":    _r("Videos", "Standard",  "video/x-msvideo",      "AVI video"),
    "mov":    _r("Videos", "Apple",     "video/quicktime",      "QuickTime video"),
    "wmv":    _r("Videos", "Windows",   "video/x-ms-wmv",       "Windows Media Video"),
    "flv":    _r("Videos", "Flash",     "video/x-flv",          "Flash video"),
    "webm":   _r("Videos", "Web",       "video/webm",           "WebM video"),
    "3gp":    _r("Videos", "Mobile",    "video/3gpp",           "3GP mobile video"),
    "3g2":    _r("Videos", "Mobile",    "video/3gpp2",          "3G2 mobile video"),
    "ts":     _r("Videos", "Stream",    "video/mp2t",           "MPEG-TS stream"),
    "mts":    _r("Videos", "Stream",    "video/mp2t",           "AVCHD stream"),
    "m2ts":   _r("Videos", "Stream",    "video/mp2t",           "Blu-ray stream"),
    "vob":    _r("Videos", "DVD",       "video/dvd",            "DVD video"),
    "mpg":    _r("Videos", "Legacy",    "video/mpeg",           "MPEG video"),
    "mpeg":   _r("Videos", "Legacy",    "video/mpeg",           "MPEG video"),
    "m2v":    _r("Videos", "Legacy",    "video/mpeg",           "MPEG-2 video"),
    "ogv":    _r("Videos", "Open",      "video/ogg",            "Ogg video"),
    "rm":     _r("Videos", "Legacy",    "application/vnd.rn-realmedia","RealMedia"),
    "rmvb":   _r("Videos", "Legacy",    "application/vnd.rn-realmedia-vbr","RealMedia VBR"),

    # ── Audio ────────────────────────────────────────────────────────────────
    "mp3":    _r("Audio", "Compressed", "audio/mpeg",           "MP3 audio"),
    "flac":   _r("Audio", "Lossless",   "audio/flac",           "FLAC audio"),
    "wav":    _r("Audio", "Lossless",   "audio/wav",            "WAV audio"),
    "aac":    _r("Audio", "Compressed", "audio/aac",            "AAC audio"),
    "m4a":    _r("Audio", "Apple",      "audio/x-m4a",          "Apple audio"),
    "ogg":    _r("Audio", "Open",       "audio/ogg",            "Ogg Vorbis"),
    "opus":   _r("Audio", "Compressed", "audio/opus",           "Opus audio"),
    "wma":    _r("Audio", "Windows",    "audio/x-ms-wma",       "Windows Media Audio"),
    "aiff":   _r("Audio", "Lossless",   "audio/aiff",           "AIFF audio"),
    "aif":    _r("Audio", "Lossless",   "audio/aiff",           "AIFF audio"),
    "mid":    _r("Audio", "MIDI",       "audio/midi",           "MIDI"),
    "midi":   _r("Audio", "MIDI",       "audio/midi",           "MIDI"),
    "ape":    _r("Audio", "Lossless",   "audio/x-ape",          "Monkey's Audio"),
    "wv":     _r("Audio", "Lossless",   "audio/x-wavpack",      "WavPack"),
    "dts":    _r("Audio", "Lossless",   "audio/vnd.dts",        "DTS audio"),
    "ac3":    _r("Audio", "Compressed", "audio/ac3",            "Dolby AC-3"),
    "amr":    _r("Audio", "Mobile",     "audio/amr",            "AMR audio"),

    # ── Documents ────────────────────────────────────────────────────────────
    "pdf":    _r("Documents", "PDF",        "application/pdf",   "PDF document"),
    "doc":    _r("Documents", "Word",       "application/msword","Word document"),
    "docx":   _r("Documents", "Word",       "application/vnd.openxmlformats-officedocument.wordprocessingml.document","Word (OOXML)"),
    "docm":   _r("Documents", "Word",       "application/vnd.ms-word.document.macroEnabled.12","Word macro"),
    "xls":    _r("Documents", "Spreadsheet","application/vnd.ms-excel","Excel spreadsheet"),
    "xlsx":   _r("Documents", "Spreadsheet","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Excel (OOXML)"),
    "xlsm":   _r("Documents", "Spreadsheet","application/vnd.ms-excel.sheet.macroEnabled.12","Excel macro"),
    "ppt":    _r("Documents", "Presentation","application/vnd.ms-powerpoint","PowerPoint"),
    "pptx":   _r("Documents", "Presentation","application/vnd.openxmlformats-officedocument.presentationml.presentation","PowerPoint (OOXML)"),
    "odt":    _r("Documents", "OpenDocument","application/vnd.oasis.opendocument.text","ODF text"),
    "ods":    _r("Documents", "OpenDocument","application/vnd.oasis.opendocument.spreadsheet","ODF spreadsheet"),
    "odp":    _r("Documents", "OpenDocument","application/vnd.oasis.opendocument.presentation","ODF presentation"),
    "txt":    _r("Documents", "Text",       "text/plain",        "Plain text"),
    "rtf":    _r("Documents", "Text",       "application/rtf",   "Rich Text Format"),
    "md":     _r("Documents", "Markdown",   "text/markdown",     "Markdown"),
    "mdx":    _r("Documents", "Markdown",   "text/markdown",     "MDX"),
    "rst":    _r("Documents", "Markup",     "text/x-rst",        "reStructuredText"),
    "adoc":   _r("Documents", "Markup",     "text/asciidoc",     "AsciiDoc"),
    "tex":    _r("Documents", "LaTeX",      "application/x-latex","LaTeX"),
    "bib":    _r("Documents", "LaTeX",      "text/x-bibtex",     "BibTeX"),
    "epub":   _r("Documents", "Ebook",      "application/epub+zip","EPUB ebook"),
    "mobi":   _r("Documents", "Ebook",      "application/x-mobipocket-ebook","MOBI ebook"),
    "azw3":   _r("Documents", "Ebook",      "application/vnd.amazon.ebook","Kindle ebook"),
    "djvu":   _r("Documents", "Ebook",      "image/vnd.djvu",    "DjVu document"),

    # ── Code ────────────────────────────────────────────────────────────────
    "py":     _r("Code", "Python",      "text/x-python",        "Python script"),
    "pyw":    _r("Code", "Python",      "text/x-python",        "Python (windowed)"),
    "pyi":    _r("Code", "Python",      "text/x-python",        "Python type stub"),
    "ipynb":  _r("Code", "Python",      "application/x-ipynb+json","Jupyter notebook"),
    "js":     _r("Code", "JavaScript",  "text/javascript",      "JavaScript"),
    "mjs":    _r("Code", "JavaScript",  "text/javascript",      "ES module"),
    "cjs":    _r("Code", "JavaScript",  "text/javascript",      "CommonJS module"),
    "jsx":    _r("Code", "JavaScript",  "text/jsx",             "JSX"),
    "ts":     _r("Code", "TypeScript",  "text/typescript",      "TypeScript"),
    "tsx":    _r("Code", "TypeScript",  "text/tsx",             "TSX"),
    "mts":    _r("Code", "TypeScript",  "text/typescript",      "TS ES module"),
    "html":   _r("Code", "Web",         "text/html",            "HTML"),
    "htm":    _r("Code", "Web",         "text/html",            "HTML"),
    "xhtml":  _r("Code", "Web",         "application/xhtml+xml","XHTML"),
    "css":    _r("Code", "Web",         "text/css",             "CSS stylesheet"),
    "scss":   _r("Code", "Web",         "text/x-scss",          "SCSS stylesheet"),
    "sass":   _r("Code", "Web",         "text/x-sass",          "Sass stylesheet"),
    "less":   _r("Code", "Web",         "text/x-less",          "Less stylesheet"),
    "java":   _r("Code", "Java",        "text/x-java-source",   "Java source"),
    "kt":     _r("Code", "Kotlin",      "text/x-kotlin",        "Kotlin source"),
    "kts":    _r("Code", "Kotlin",      "text/x-kotlin",        "Kotlin script"),
    "groovy": _r("Code", "JVM",         "text/x-groovy",        "Groovy script"),
    "scala":  _r("Code", "JVM",         "text/x-scala",         "Scala source"),
    "clj":    _r("Code", "JVM",         "text/x-clojure",       "Clojure source"),
    "c":      _r("Code", "C_Cpp",       "text/x-csrc",          "C source"),
    "cpp":    _r("Code", "C_Cpp",       "text/x-c++src",        "C++ source"),
    "cc":     _r("Code", "C_Cpp",       "text/x-c++src",        "C++ source"),
    "cxx":    _r("Code", "C_Cpp",       "text/x-c++src",        "C++ source"),
    "h":      _r("Code", "C_Cpp",       "text/x-chdr",          "C/C++ header"),
    "hpp":    _r("Code", "C_Cpp",       "text/x-c++hdr",        "C++ header"),
    "hxx":    _r("Code", "C_Cpp",       "text/x-c++hdr",        "C++ header"),
    "cs":     _r("Code", "CSharp",      "text/x-csharp",        "C# source"),
    "fs":     _r("Code", "FSharp",      "text/x-fsharp",        "F# source"),
    "vb":     _r("Code", "VB.NET",      "text/x-vba",           "VB.NET source"),
    "go":     _r("Code", "Go",          "text/x-go",            "Go source"),
    "rs":     _r("Code", "Rust",        "text/x-rustsrc",       "Rust source"),
    "rb":     _r("Code", "Ruby",        "text/x-ruby",          "Ruby script"),
    "php":    _r("Code", "PHP",         "text/x-php",           "PHP script"),
    "php3":   _r("Code", "PHP",         "text/x-php",           "PHP script"),
    "php4":   _r("Code", "PHP",         "text/x-php",           "PHP script"),
    "php5":   _r("Code", "PHP",         "text/x-php",           "PHP script"),
    "phtml":  _r("Code", "PHP",         "text/x-php",           "PHP template"),
    "swift":  _r("Code", "Swift",       "text/x-swift",         "Swift source"),
    "m":      _r("Code", "ObjC",        "text/x-objcsrc",       "Objective-C source"),
    "mm":     _r("Code", "ObjC",        "text/x-objc++src",     "Objective-C++ source"),
    "r":      _r("Code", "R",           "text/x-r",             "R script"),
    "rmd":    _r("Code", "R",           "text/x-rmarkdown",     "R Markdown"),
    "lua":    _r("Code", "Lua",         "text/x-lua",           "Lua script"),
    "sh":     _r("Code", "Shell",       "application/x-sh",     "Shell script"),
    "bash":   _r("Code", "Shell",       "application/x-sh",     "Bash script"),
    "zsh":    _r("Code", "Shell",       "application/x-sh",     "Zsh script"),
    "fish":   _r("Code", "Shell",       "application/x-sh",     "Fish script"),
    "ps1":    _r("Code", "PowerShell",  "application/x-powershell","PowerShell script"),
    "psm1":   _r("Code", "PowerShell",  "application/x-powershell","PowerShell module"),
    "psd1":   _r("Code", "PowerShell",  "application/x-powershell","PowerShell data"),
    "sql":    _r("Code", "SQL",         "application/sql",      "SQL query"),
    "dart":   _r("Code", "Dart",        "application/dart",     "Dart source"),
    "ex":     _r("Code", "Elixir",      "text/x-elixir",        "Elixir source"),
    "exs":    _r("Code", "Elixir",      "text/x-elixir",        "Elixir script"),
    "hs":     _r("Code", "Haskell",     "text/x-haskell",       "Haskell source"),
    "lhs":    _r("Code", "Haskell",     "text/x-literate-haskell","Literate Haskell"),
    "ml":     _r("Code", "OCaml",       "text/x-ocaml",         "OCaml source"),
    "mli":    _r("Code", "OCaml",       "text/x-ocaml",         "OCaml interface"),
    "elm":    _r("Code", "Elm",         "text/x-elm",           "Elm source"),
    "vue":    _r("Code", "Vue",         "text/x-vue",           "Vue component"),
    "svelte": _r("Code", "Svelte",      "text/x-svelte",        "Svelte component"),
    "astro":  _r("Code", "Astro",       "text/x-astro",         "Astro component"),
    "tf":     _r("Code", "Terraform",   "text/x-terraform",     "Terraform config"),
    "tfvars": _r("Code", "Terraform",   "text/x-terraform",     "Terraform vars"),
    "bicep":  _r("Code", "Azure",       "text/x-bicep",         "Bicep template"),
    "zig":    _r("Code", "Zig",         "text/x-zig",           "Zig source"),
    "nim":    _r("Code", "Nim",         "text/x-nim",           "Nim source"),
    "cr":     _r("Code", "Crystal",     "text/x-crystal",       "Crystal source"),
    "jl":     _r("Code", "Julia",       "text/x-julia",         "Julia source"),
    "pl":     _r("Code", "Perl",        "text/x-perl",          "Perl script"),
    "pm":     _r("Code", "Perl",        "text/x-perl",          "Perl module"),
    "perl":   _r("Code", "Perl",        "text/x-perl",          "Perl script"),
    "tcl":    _r("Code", "Tcl",         "text/x-tcl",           "Tcl script"),
    "coffee": _r("Code", "CoffeeScript","text/coffeescript",     "CoffeeScript"),

    # ── Data ────────────────────────────────────────────────────────────────
    "json":   _r("Data", "JSON",        "application/json",     "JSON data"),
    "jsonc":  _r("Data", "JSON",        "application/json",     "JSON with comments"),
    "json5":  _r("Data", "JSON",        "application/json5",    "JSON5 data"),
    "ndjson": _r("Data", "JSON",        "application/x-ndjson", "Newline-delimited JSON"),
    "jsonl":  _r("Data", "JSON",        "application/x-ndjson", "JSON Lines"),
    "xml":    _r("Data", "XML",         "application/xml",      "XML data"),
    "xsd":    _r("Data", "XML",         "application/xml",      "XML schema"),
    "xsl":    _r("Data", "XML",         "application/xslt+xml", "XSLT stylesheet"),
    "xslt":   _r("Data", "XML",         "application/xslt+xml", "XSLT stylesheet"),
    "yaml":   _r("Data", "YAML",        "application/x-yaml",   "YAML data"),
    "yml":    _r("Data", "YAML",        "application/x-yaml",   "YAML data"),
    "csv":    _r("Data", "Tabular",     "text/csv",             "CSV data"),
    "tsv":    _r("Data", "Tabular",     "text/tab-separated-values","TSV data"),
    "toml":   _r("Data", "Config",      "application/toml",     "TOML config"),
    "ini":    _r("Data", "Config",      "text/plain",           "INI config"),
    "cfg":    _r("Data", "Config",      "text/plain",           "Config file"),
    "conf":   _r("Data", "Config",      "text/plain",           "Config file"),
    "env":    _r("Data", "Config",      "text/plain",           "Environment file"),
    "plist":  _r("Data", "Config",      "application/x-plist",  "Property list"),
    "proto":  _r("Data", "Protobuf",    "text/x-protobuf",      "Protocol Buffers"),
    "graphql":_r("Data", "GraphQL",     "application/graphql",  "GraphQL schema"),
    "gql":    _r("Data", "GraphQL",     "application/graphql",  "GraphQL query"),
    "parquet":_r("Data", "Analytics",   "application/octet-stream","Apache Parquet"),
    "avro":   _r("Data", "Analytics",   "application/octet-stream","Apache Avro"),
    "orc":    _r("Data", "Analytics",   "application/octet-stream","ORC columnar"),
    "feather":_r("Data", "Analytics",   "application/octet-stream","Arrow Feather"),
    "hdf5":   _r("Data", "Analytics",   "application/x-hdf5",   "HDF5 dataset"),
    "h5":     _r("Data", "Analytics",   "application/x-hdf5",   "HDF5 dataset"),
    "sqlite": _r("Data", "Database",    "application/x-sqlite3","SQLite database"),
    "sqlite3":_r("Data", "Database",    "application/x-sqlite3","SQLite database"),
    "db":     _r("Data", "Database",    "application/x-sqlite3","Database file"),
    "mdb":    _r("Data", "Database",    "application/x-msaccess","Access database"),
    "accdb":  _r("Data", "Database",    "application/x-msaccess","Access database"),
    "geojson":_r("Data", "Geo",         "application/geo+json", "GeoJSON"),
    "shp":    _r("Data", "Geo",         "application/x-esri-shape","Shapefile"),
    "kml":    _r("Data", "Geo",         "application/vnd.google-earth.kml+xml","KML geo"),
    "gpx":    _r("Data", "Geo",         "application/gpx+xml",  "GPS track"),

    # ── Archives ─────────────────────────────────────────────────────────────
    "zip":    _r("Archives", "ZIP",     "application/zip",            "ZIP archive"),
    "tar":    _r("Archives", "TAR",     "application/x-tar",          "TAR archive"),
    "gz":     _r("Archives", "GZ",      "application/gzip",           "Gzip archive"),
    "tgz":    _r("Archives", "TAR+GZ",  "application/x-compressed-tar","Tar+Gzip"),
    "bz2":    _r("Archives", "BZ2",     "application/x-bzip2",        "Bzip2 archive"),
    "tbz2":   _r("Archives", "TAR+BZ2", "application/x-bzip2-compressed-tar","Tar+Bzip2"),
    "xz":     _r("Archives", "XZ",      "application/x-xz",           "XZ archive"),
    "txz":    _r("Archives", "TAR+XZ",  "application/x-xz-compressed-tar","Tar+XZ"),
    "zst":    _r("Archives", "Zstd",    "application/zstd",           "Zstandard archive"),
    "lz4":    _r("Archives", "LZ4",     "application/x-lz4",          "LZ4 archive"),
    "7z":     _r("Archives", "7Z",      "application/x-7z-compressed","7-Zip archive"),
    "rar":    _r("Archives", "RAR",     "application/vnd.rar",        "RAR archive"),
    "cab":    _r("Archives", "CAB",     "application/vnd.ms-cab-compressed","MS Cabinet"),
    "iso":    _r("Archives", "Disk",    "application/x-iso9660-image","ISO disk image"),
    "dmg":    _r("Archives", "Disk",    "application/x-apple-diskimage","macOS disk"),
    "img":    _r("Archives", "Disk",    "application/x-raw-disk-image","Disk image"),
    "vhd":    _r("Archives", "Disk",    "application/x-vhd",          "VHD disk image"),
    "vmdk":   _r("Archives", "Disk",    "application/x-vmdk",         "VMware disk"),
    "qcow2":  _r("Archives", "Disk",    "application/x-qemu-disk",    "QEMU disk"),

    # ── Executables ──────────────────────────────────────────────────────────
    "exe":    _r("Executables", "Windows","application/x-msdownload","Windows executable"),
    "msi":    _r("Executables", "Windows","application/x-msi",      "Windows installer"),
    "dll":    _r("Executables", "Windows","application/x-msdownload","Windows library"),
    "sys":    _r("Executables", "Windows","application/octet-stream","Windows driver"),
    "bat":    _r("Executables", "Windows","application/x-bat",      "Windows batch"),
    "cmd":    _r("Executables", "Windows","application/x-bat",      "Windows command"),
    "com":    _r("Executables", "Windows","application/x-dosexec",  "DOS executable"),
    "scr":    _r("Executables", "Windows","application/x-dosexec",  "Windows screensaver"),
    "apk":    _r("Executables", "Android","application/vnd.android.package-archive","APK"),
    "aab":    _r("Executables", "Android","application/x-authorware-bin","Android bundle"),
    "ipa":    _r("Executables", "iOS",    "application/x-ios-app",  "iOS app"),
    "app":    _r("Executables", "macOS",  "application/x-apple-app","macOS app"),
    "pkg":    _r("Executables", "macOS",  "application/x-newton-compatible-pkg","macOS pkg"),
    "deb":    _r("Executables", "Linux",  "application/x-debian-package","Debian package"),
    "rpm":    _r("Executables", "Linux",  "application/x-rpm",      "RPM package"),
    "appimage":_r("Executables","Linux",  "application/x-executable","AppImage"),
    "snap":   _r("Executables", "Linux",  "application/x-snap",     "Snap package"),
    "flatpak":_r("Executables", "Linux",  "application/x-flatpak",  "Flatpak bundle"),
    "bin":    _r("Executables", "Binary", "application/octet-stream","Binary file"),
    "run":    _r("Executables", "Binary", "application/x-executable","Runnable binary"),
    "elf":    _r("Executables", "Binary", "application/x-elf",      "ELF binary"),
    "wasm":   _r("Executables", "WASM",   "application/wasm",       "WebAssembly"),

    # ── Fonts ───────────────────────────────────────────────────────────────
    "ttf":    _r("Fonts", "TrueType",   "font/ttf",             "TrueType font"),
    "otf":    _r("Fonts", "OpenType",   "font/otf",             "OpenType font"),
    "woff":   _r("Fonts", "Web",        "font/woff",            "Web font (WOFF)"),
    "woff2":  _r("Fonts", "Web",        "font/woff2",           "Web font (WOFF2)"),
    "eot":    _r("Fonts", "Web",        "application/vnd.ms-fontobject","Embedded OT"),
    "fon":    _r("Fonts", "Legacy",     "application/x-font",   "Windows raster font"),

    # ── 3D / CAD ─────────────────────────────────────────────────────────────
    "obj":    _r("3D", "Mesh",          "model/obj",            "Wavefront OBJ"),
    "fbx":    _r("3D", "Mesh",          "application/octet-stream","Autodesk FBX"),
    "stl":    _r("3D", "Mesh",          "model/stl",            "STL 3D model"),
    "3mf":    _r("3D", "Mesh",          "model/3mf",            "3D Manufacturing Format"),
    "ply":    _r("3D", "Mesh",          "application/octet-stream","PLY mesh"),
    "blend":  _r("3D", "Blender",       "application/x-blender","Blender project"),
    "dae":    _r("3D", "Collada",       "model/vnd.collada+xml","Collada 3D"),
    "glb":    _r("3D", "GLTF",          "model/gltf-binary",   "glTF binary"),
    "gltf":   _r("3D", "GLTF",          "model/gltf+json",     "glTF JSON"),
    "step":   _r("3D", "CAD",           "application/step",    "STEP CAD file"),
    "stp":    _r("3D", "CAD",           "application/step",    "STEP CAD file"),
    "iges":   _r("3D", "CAD",           "model/iges",          "IGES CAD file"),
    "igs":    _r("3D", "CAD",           "model/iges",          "IGES CAD file"),
    "dwg":    _r("3D", "CAD",           "image/vnd.dwg",       "AutoCAD drawing"),
    "dxf":    _r("3D", "CAD",           "image/vnd.dxf",       "AutoCAD exchange"),
    "usdz":   _r("3D", "AR",            "model/vnd.usdz+zip",  "AR Quick Look"),

    # ── Design ───────────────────────────────────────────────────────────────
    "fig":    _r("Design", "Figma",     "application/octet-stream","Figma design"),
    "sketch": _r("Design", "Sketch",    "application/octet-stream","Sketch design"),
    "xd":     _r("Design", "AdobeXD",  "application/octet-stream","Adobe XD"),
    "indd":   _r("Design", "InDesign",  "application/x-indesign","InDesign doc"),
    "idml":   _r("Design", "InDesign",  "application/vnd.adobe.indesign-idml-package","InDesign markup"),
    "afdesign":_r("Design","Affinity",  "application/octet-stream","Affinity Designer"),
    "afphoto":_r("Design", "Affinity",  "application/octet-stream","Affinity Photo"),
    "afpub":  _r("Design", "Affinity",  "application/octet-stream","Affinity Publisher"),

    # ── Logs & Temp ──────────────────────────────────────────────────────────
    "log":    _r("Logs", "Text",        "text/plain",           "Log file"),
    "out":    _r("Logs", "Output",      "text/plain",           "Output log"),
    "err":    _r("Logs", "Error",       "text/plain",           "Error log"),
    "tmp":    _r("Temp", "Temporary",   "application/octet-stream","Temp file"),
    "temp":   _r("Temp", "Temporary",   "application/octet-stream","Temp file"),
    "bak":    _r("Temp", "Backup",      "application/octet-stream","Backup file"),
    "old":    _r("Temp", "Backup",      "application/octet-stream","Old file"),
    "swp":    _r("Temp", "Editor",      "application/octet-stream","Vim swap file"),
    "swo":    _r("Temp", "Editor",      "application/octet-stream","Vim swap file"),

    # ── Dev / Build ──────────────────────────────────────────────────────────
    "lock":      _r("Dev", "Lockfile",  "text/plain",           "Dependency lockfile"),
    "gitignore": _r("Dev", "Git",       "text/plain",           ".gitignore"),
    "gitattributes":_r("Dev","Git",     "text/plain",           ".gitattributes"),
    "gitmodules":_r("Dev", "Git",       "text/plain",           "Git submodules"),
    "editorconfig":_r("Dev","Config",   "text/plain",           ".editorconfig"),
    "prettierrc":_r("Dev", "Config",    "text/plain",           "Prettier config"),
    "eslintrc":  _r("Dev", "Config",    "text/plain",           "ESLint config"),
    "babelrc":   _r("Dev", "Config",    "text/plain",           "Babel config"),
    "nvmrc":     _r("Dev", "Config",    "text/plain",           "NVM version file"),
    "dockerfile":_r("Dev", "Docker",    "text/plain",           "Dockerfile"),
    "makefile":  _r("Dev", "Build",     "text/x-makefile",      "Makefile"),
    "gradle":    _r("Dev", "Build",     "text/x-groovy",        "Gradle build"),
    "cmake":     _r("Dev", "Build",     "text/x-cmake",         "CMake build"),
    "pom":       _r("Dev", "Build",     "application/xml",      "Maven POM"),
    "bazel":     _r("Dev", "Build",     "text/plain",           "Bazel build"),
    "bzl":       _r("Dev", "Build",     "text/plain",           "Bazel extension"),
    "nix":       _r("Dev", "Build",     "text/x-nix",           "Nix expression"),
    "flake":     _r("Dev", "Build",     "text/x-nix",           "Nix flake"),
    "gemspec":   _r("Dev", "Ruby",      "text/x-ruby",          "RubyGem spec"),
    "podspec":   _r("Dev", "iOS",       "text/x-ruby",          "CocoaPods spec"),

    # ── Security / Crypto ────────────────────────────────────────────────────
    "pem":    _r("Security", "Certificate","application/x-pem-file","PEM certificate"),
    "crt":    _r("Security", "Certificate","application/x-x509-ca-cert","Certificate"),
    "cer":    _r("Security", "Certificate","application/x-x509-ca-cert","Certificate"),
    "der":    _r("Security", "Certificate","application/x-x509-ca-cert","DER certificate"),
    "key":    _r("Security", "Key",      "application/x-pem-file","Private key"),
    "pub":    _r("Security", "Key",      "application/x-pem-file","Public key"),
    "p12":    _r("Security", "Keystore", "application/x-pkcs12","PKCS12 keystore"),
    "pfx":    _r("Security", "Keystore", "application/x-pkcs12","PFX keystore"),
    "jks":    _r("Security", "Keystore", "application/x-java-keystore","Java keystore"),
    "gpg":    _r("Security", "PGP",      "application/pgp-encrypted","GPG file"),
    "sig":    _r("Security", "Signature","application/pgp-signature","Signature"),

    # ── System ───────────────────────────────────────────────────────────────
    "so":     _r("System", "Library",   "application/x-sharedlib","Shared library"),
    "a":      _r("System", "Library",   "application/x-archive","Static library"),
    "lib":    _r("System", "Library",   "application/x-archive","Library"),
    "o":      _r("System", "Object",    "application/x-object","Object file"),
    "ko":     _r("System", "Kernel",    "application/x-object","Kernel module"),
    "map":    _r("System", "SourceMap", "application/json",    "Source map"),
    "pdb":    _r("System", "Debug",     "application/x-pdb",   "Debug symbols"),
    "sym":    _r("System", "Debug",     "application/octet-stream","Symbol file"),

    # ── Subtitles / Captions ─────────────────────────────────────────────────
    "srt":    _r("Subtitles", "Text",   "application/x-subrip","SRT subtitles"),
    "vtt":    _r("Subtitles", "Web",    "text/vtt",            "WebVTT subtitles"),
    "ass":    _r("Subtitles", "Advanced","text/x-ssa",         "ASS subtitles"),
    "ssa":    _r("Subtitles", "Advanced","text/x-ssa",         "SSA subtitles"),
    "sub":    _r("Subtitles", "Text",   "text/plain",          "Subtitle file"),
}

UNKNOWN_RULE = Rule("Uncategorized", "Unknown", "application/octet-stream", "Unknown file type")
